# Generated by Django 4.2.23 on 2025-07-02 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
        migrations.CreateModel(
            name="PostStatusRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_changed", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.post",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.post_status",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.ManyToManyField(
                through="marketplace.PostStatusRelation", to="marketplace.post_status"
            ),
        ),
    ]
