# Generated by Django 4.2.23 on 2025-06-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("quality", models.CharField(blank=True, max_length=100, null=True)),
                ("harvest_date", models.DateField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("is_seasonal", models.BooleanField(default=False)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="marketplace.product",
                    ),
                ),
            ],
        ),
    ]
