# Generated by Django 4.2.23 on 2025-06-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_productdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Post_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name="Status",
            new_name="Message_status",
        ),
        migrations.DeleteModel(
            name="ProductDetail",
        ),
        migrations.AddField(
            model_name="post",
            name="labels",
            field=models.ManyToManyField(blank=True, to="marketplace.label"),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="marketplace.post_status",
            ),
        ),
    ]
