# Generated by Django 4.2.23 on 2025-07-07 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_bid_bid_status_bidstatusrelation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BidStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Statut d'enchère",
                "verbose_name_plural": "Statuts d'enchères",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="bid",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="bidstatusrelation",
            options={"ordering": ["-date_changed"]},
        ),
        migrations.RemoveField(
            model_name="bid",
            name="id_post",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="id_user",
        ),
        migrations.AddField(
            model_name="bid",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bid",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.currency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="marketplace.post",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="bid",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bidstatusrelation",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bid_status_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bidstatusrelation",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bid",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bidstatusrelation",
            name="bid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_relations",
                to="marketplace.bid",
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["post", "-created_at"], name="marketplace_post_id_7f440b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["user", "-created_at"], name="marketplace_user_id_7139c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bidstatusrelation",
            index=models.Index(
                fields=["bid", "-date_changed"], name="marketplace_bid_id_f7fd69_idx"
            ),
        ),
        migrations.AlterField(
            model_name="bidstatusrelation",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="marketplace.bidstatus"
            ),
        ),
        migrations.DeleteModel(
            name="Bid_status",
        ),
    ]
