# Generated by Django 4.2.23 on 2025-07-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_alter_post_status_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_status",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
